---
- name: Check if system has a subscription attached
  shell: subscription-manager status | grep Current
  register: subscription_status
  ignore_errors: yes

- name: Subscribe using username and password
  redhat_subscription:
    username: "{{ redhat_subscription_username }}"
    password: "{{ redhat_subscription_password }}"
    autosubscribe: yes
    force_register: "{{redhat_subscription_force_register | default(no) }}"
  when: redhat_subscription_username is defined and redhat_subscription_password is defined and redhat_subscription_activationkey is not defined and subscription_status.rc == 1

- name: Subscribe using activationkey
  redhat_subscription:
    org_id: "{{ redhat_subscription_org_id }}"
    activationkey: "{{ redhat_subscription_activationkey }}"
    autosubscribe: yes
    force_register: "{{redhat_subscription_force_register | default(no) }}"
  when: redhat_subscription_username is not defined and redhat_subscription_password is not defined and redhat_subscription_activationkey is defined and subscription_status.rc == 1

- name: Enable Red Hat Repos
  shell: "subscription-manager repos --enable {{ item }}"
  with_items: "{{ redhat_subscription_repositories }}"
  tags:
    - Deployment

- name: Update packages.
  yum:
    name: "*"
    state: latest
