---
- name: Subscription
  redhat_subscription:
    username: "{{ redhat_subscription_username }}"
    password: "{{ redhat_subscription_password }}"
    consumer_type: "{{ redhat_subscription_ }}"
    org_id: "{{ redhat_subscription_org_id }}"
    pool_ids: "{{ redhat_subscription_pool_ids }}"
    consumer_id: "{{ redhat_subscription_consumer_id }}"
    activationkey: "{{ redhat_subscription_activationkey }}"
    autosubscribe: yes
    force_register: yes
    environment: "{{ redhat_subscription_environment }}"
  when: redhat_subscription_subscribe is defined and redhat_subscription_subscribe
  tags:
    - Deployment



- name: Enable Red Hat Repos
  shell: "subscription-manager repos --enable {{ item }}"
  with_items: "{{ redhat_subscription_repositories }}"
  tags:
    - Deployment

- name: Get the current kernel release.
  command: uname -r
  changed_when: false
  register: kernel_release
  tags:
    - Deployment
